### ISSUE TITLE
"The following resources are not up to date....." When printing to PDF

### ISSUE THREAD

**Issue by ckuhnMPLS** [pyrevitlabs/pyRevit#1533]
**Describe the bug**
The default printer is BlueBeam. This keynote file is hosted on BIM 360 and linked into a project with multiple models (7 arch Revit 2021 files)

Obviously tried to reload, but you have to click continue on each sheet that's being printed. 

**Screenshots**
![Pyrevit - Update Res](https://user-images.githubusercontent.com/94191506/168664635-f65c301e-4d0d-44ed-b5dd-b05371c27f24.png)

**Desktop (please complete the following information):**
Windows 10
Revit 2021
[pyRevit 4.8.10.22040 Installer](https://github.com/eirannejad/pyRevit/releases/download/v4.8.10.22040%2B1743/pyRevit_4.8.10.22040_admin_signed.exe) - Admin / All Users / %PROGRAMDATA%

**Comment by HyperHipon** [comment]
Hi! I'm having the same problem as well when I try to batch print on pyrevit. We get prompted on every sheet when printing them individually. On our case, we use cute pdf as the pdf writer.

Desktop (please complete the following information):
Windows 10
Revit 2019
[pyRevit 4.8.10.22040 Installer](https://github.com/eirannejad/pyRevit/releases/download/v4.8.10.22040%2B1743/pyRevit_4.8.10.22040_admin_signed.exe) - Admin / All Users / %PROGRAMDATA%

**Comment by mpguru66** [comment]
We're currently getting this message when printing. Is there a solution / fix?

**Comment by srs07arch** [comment]
I am currently having this issue.  Revit 2024.2, pyRevit v4.8.13.23182+2215
This issue is closed but is marked as completed.  Is there a fix?
I have tried reloading through pyRevit keynote manager before printing as well as reloading throughRevit Keynoting Settings before printing and still get the same error message.

**Comment by jmcouffin** [comment]
Not sure it is fixed, but pretty sure you need to update

Please uninstall old version and download WIP installers from the actions tab or from the https://pyrevitlabs.io website using the orange button and report.

**Comment by srs07arch** [comment]
I have completed these steps, but I am still getting this error:
***@***.***


Thank you,

SHELLY STRANGE | ARCHITECT
***@***.***
301 Jackson Street | Suite 205 | Alexandria, LA  71301 | 318.473.0252
e-mail | ***@***.******@***.***>
website | abwarchitects.com<http://www.abwarchitects.com/>

**Comment by jmcouffin** [comment]
The tool has been extensively refactored since then

**Comment by mpguru66** [comment]
Thank you Jean-Marc. Would you recommend uninstalling and reinstalling?

Mark

**Comment by jmcouffin** [comment]
> Thank you Jean-Marc. Would you recommend uninstalling and reinstalling?
> 
> Mark
> […](#)

Yes, uninstall first. Always.
